### ISSUE TITLE
Are Tlist etc thread safe?

### ISSUE THREAD

**Issue by AnthonyLloyd** [bryanedds/Nu#166]
Just thinking about a write thread and read running at the same time. 

If they both get the original list from validate but the write thread updates ImpList before the read. Then the read thread will see this update and later see it without the update if it reruns and validate calls commit and rebuilds from the logs.

**Comment by bryanedds** [comment]
Sorry, I just now saw this. I don't know why github isn't notifying me a new issues...

But anyways, I don't think that these data structures are thread-safe with any sort of reasonable performance guarantees. They might be, but unless someone can prove that they are, I would assume otherwise.

If you want thread-safety, I would recommend sticking with the library primitives of list, Set, and Map.
