### ISSUE TITLE
Autocomplete Not Working for Entity Type Extensions in User-Created Projects

### ISSUE THREAD

**Issue by nanodesu88** [bryanedds/Nu#233]
Where is autocomplete for Entity, Layer etc types? I am using rider + vs and they both can't detect a Entity members. How can we effective use a library when we cannot see what we have inside?

**Comment by bryanedds** [comment]
Currently, this form of auto-complete is only available in Visual Studio 2017 due to limitations in other plug-ins.

It looks like you would need to send in a feature request to the rider team along the lines of "FEATURE REQUEST: Please implement auto-complete for F# Type Extensions." There's no reason they shouldn't be able to get this done.

Thanks!

**Comment by bryanedds** [comment]
Alternatively, the issue might instead be that you have an unannotated reference that needs to have its type annotated as such -

```
    let someFunction (entity : Entity) world =
        entity.GetPosition world + entity.GetSize world
```

But I really think your issue is most likely a plug-in with an incomplete feature set.

**Comment by bryanedds** [comment]
Okay, the official line is -

Only Visual Studio 2017 is currently supported for Nu game development. Any other editing tools are unsupported and used at your discretion.

NOTE: I just downloaded and tried Rider with F# - it doesn't even appear to support basic F# syntax highlighting, much less autocomplete. If this is the typical F# experience in Rider, I recommend that you not use it for anything related to F#. Stick with Visual Studio 2017.

**Comment by nanodesu88** [comment]
VS2017 do not wants to autocomplete entity
https://yadi.sk/i/Va0yGJFWieIiAg
https://yadi.sk/i/BphtJcvhBDmYDQ

**Comment by bryanedds** [comment]
The above links do not work, I'm afraid.

**Comment by bryanedds** [comment]
Did you install Visual F# Tools in Visual Studio 2017? I think that plug-in is required to make full use of F#'s features.

**Comment by bryanedds** [comment]
Okay, so I didn't realize that I am having the same issue locally. Apparently, for some reason, auto-complete does not work for Entity type extensions outside of the main Nu project. This appears to be a bug in the F# Tools plug-in itself!

I'm going to look into fixing this myself because autocomplete is necessary for this engine to even be usable.

**Comment by nanodesu88** [comment]
Sorry, i have delete screenshots. Yes, Layer autocomplete works, Entity does not.

**Comment by nanodesu88** [comment]
Gonna to report this bug yesterday

**Comment by bryanedds** [comment]
Reported to F# tools team here -

https://github.com/dotnet/fsharp/issues/7073

**Comment by bryanedds** [comment]
Closed with work-around.
