### ISSUE TITLE
Nuget packages

### ISSUE THREAD

**Issue by nanodesu88** [bryanedds/Nu#236]
Why Nu have hard links to nuget packages dll? I am trying to make a project which uses Nu sources as git submodule (root/Nu/Nu/Nu.fsproj) and Nu's dependencies has broken in this case, because Nu.fsproj have hard links ../../packages to Nuget packages

**Comment by bryanedds** [comment]
Those are relative links, so if you include everything from the repository, they will exist where they're supposed to.

It looks like you're trying to do too many custom things that I can't support without chatting over Google Hangouts.

Would you mind setting up a time to connect after 6P eastern time today?

**Comment by bryanedds** [comment]
Actually, maybe I misunderstood what you want.

Okay, you want the packages to be placed automatically.

The reason that doesn't work in Nu is because the projects in Nu need to share common dependencies to make it easy to debug Prime and other dependencies from source.

In truth, you shouldn't be using submodules for this. Using Nu implies forking the repository and developing out of it. There may be a workaround on your end, but I can't provide support for using the engine in a way so different from what it intended.

If you can tell me why you need a feature of submodules so we can find a workaround. Otherwise, I can't provide support.

Temporarily marking as Won't Fix, but keeping issue open for discussion.

**Comment by nanodesu88** [comment]
If i want to do some fixes in Nu, where should i commit the changes? In my fork repository with code which i don't want to commit? 
If Nu will be in separate repository, i can change the code of engine without pushing unnecessary commits of other projects

**Comment by bryanedds** [comment]
The easy solution is like the approach Unreal developers use - do your local work in a branch, and only put engine fixes that you want to contribute into `master`.

Does this sound sufficient?

**Comment by nanodesu88** [comment]
Yes, i am already start doing this way. But this method still have a problem. What if i want to use Nu (library) in another project repo?

**Comment by bryanedds** [comment]
Maybe the difficulty is in the way you're thinking about it. Nu is not a library but rather a game engine. This is a very important distinction because a game engine is a more imposing thing than a library. If you want to do multiple projects with a game engine, you keep them in the same repository, perhaps each in a different branch.

There are necessary trade-offs and constraints with using a game engine vs a library - you can't think of them as being the same thing. This is same is true for other game engines like Unreal and Unity with open source.

If you have a specific and immediate problem that I can help you solve, we can continue this issue. Otherwise, I'll close it.
