### ISSUE TITLE
World update timer

### ISSUE THREAD

**Issue by nanodesu88** [bryanedds/Nu#242]
How to manually realize a entity moving? I want to move entity (static sprite) for some units per second. Is world have a value how many time past from last event triggered?
Can you explain a example please?

**Comment by bryanedds** [comment]
Nu updates at 60 frames per second without a variable frame rate. So each update is 16.667ms. You can use that as a constant to work out the desired translation.

If you want to get the speed at which the world is ticking, you call World.getTickRate or World.getTickRateF for floating point. But again, since Nu doesn't vary its frame rate, the value will be either 1 or 0 depending on whether ticking is enabled (unless you change the tick rate yourself).

**Comment by nanodesu88** [comment]
Can tickRate be lower than 1 if engine cannot provide a constantly 60 fps due to performance issues?

**Comment by bryanedds** [comment]
By default, as long as the engine is not paused, the tick rate is 1. So if the engine goes down to 30FPS due to performance issues, the game will slow down the same way that old NES and SNES games do. In theory, the engine could automatically adjust the tick rate when frames are dropping, but I think it's better that people just optimize so their game so that frames don't drop.

**Comment by bryanedds** [comment]
Assuming this is resolved.
