### ISSUE TITLE
Facet composition and facet private properties

### ISSUE THREAD

**Issue by nanodesu88** [bryanedds/Nu#243]
Its possible to have a facet which inside operates on other facets? 
Two facets have a different properties (can be different types) with same name ("name", for example). How to workaround about it? Only with naming conversion?

**Comment by bryanedds** [comment]
In Nu, simulant properties are dynamic. So you can have a Facet operate on another Facet so long as you either check that the other Facet is being used (like with entity.FacetedAs<OtherFacetType>), or can somehow safely assume it is being used.

Because properties are dynamic, they share the same namespace. So if you want a two facets to use different properties, those properties must each have unique names. You can come up with a naming conventions if you need to.

**Comment by bryanedds** [comment]
In general, however, you cannot nest Facets. You can, however, create a Dispatcher that has multiple 'intrinsic' facets that always exist together by defining Intrinsic Facets in the Dispatcher like so -

```
    type BlockDispatcher () =
        inherit EntityDispatcher ()

        static member FacetNames =
            [typeof<RigidBodyFacet>.Name
             typeof<StaticSpriteFacet>.Name]
```

**Comment by bryanedds** [comment]
Assuming that this question is satisfactorily answered. Please re-open if not.
