### ISSUE TITLE
Build fails on archlinux monodevelop/msbuild

### ISSUE THREAD

**Issue by amiralies** [bryanedds/Nu#330]
`~/Workspace/Nu/Nu/Nu/Nu.fsproj: Error MSB4057: The target "Build" does not exist in the project. (MSB4057) (Nu)`
I've no dotnet / fsharp experience. let me know if more information is needed.

**Comment by bryanedds** [comment]
Building Nu on Linux isn't necessarily the most straight-forward thing in the world.

However, there are configuration scripts to help you set up the necessary environment for Ubuntu and Debian here -
https://github.com/bryanedds/Nu/blob/master/Configure.Ubuntu.Development.sh
https://github.com/bryanedds/Nu/blob/master/Configure.Debian.Development.sh

...as well as build scripts for Debug and Release here -
https://github.com/bryanedds/Nu/blob/master/Build.Linux.Debug.sh
https://github.com/bryanedds/Nu/blob/master/Build.Linux.Release.sh

You might be able to run them in order to build Nu in a totally automatic fashion on Arch Linux. The only thing that might vary is the Mono package sources specific to Arch Linux, which you should be able to figure out how to customize based on its specific package provider.

Please let us know if these scripts are helpful. If you get it building on Arch Linux with modifications, please post a PR with the modified Arch Linux script so that we can include it in the repository as well.

Cheers!

**Comment by bryanedds** [comment]
Closing this due to lack of follow-up. Will re-open if follow-up occurs.

**Comment by jmhimara** [comment]
I'm also having a bit of trouble with this. 

I tried compiling this on WSL Ubuntu with the provided scripts, but I keep getting a bunch of errors about `int64` and `int` types. Have not yet tried it on a native Linux install. 

Are there any plans to make it work with newer versions of dotnet core?

**Comment by bryanedds** [comment]
There is no concrete plan to put resources into porting Nu to .NET Core. It would be very nice to have, tho.
