### ISSUE TITLE
Frame rate can become choppy after Nu goes from high to low CPU utilization in StaticFrameRate mode.

### ISSUE THREAD

**Issue by bryanedds** [bryanedds/Nu#439]
I am not understanding why this happens. I've tried lots of approaches to timing and nothing has yet addressed this issue.

**Comment by bryanedds** [comment]
I wonder if this could be related to CPU throttling changes messing up resource utilization or timing somehow? I know precious little about these HW topics...

**Comment by bryanedds** [comment]
I highly suspect this is more likely a bug in my system's power management software than anything relating to Nu.

**Comment by bryanedds** [comment]
Additionally, Elmario running just by itself seems to exhibit this issue.

**Comment by reinux** [comment]
I suspect it's due to the task scheduling features in Windows 7 or so onward, which chunk together timer/sleep calls to conserve energy consumption. It definitely does that well; benchmarks showed some impressive battery life gains at the time. But it also means you have to configure it to behave well for multimedia apps.

There are ways to get it to behave, but I haven't had much success using them in Nu just yet.

I've tried setting the thread priority and thread characteristics (with the renderer set to run on the same thread) and have had no success. In Program.fs:

```
open System.Runtime.InteropServices
module Program =
  
  [<DllImport("avrt.dll")>]
  extern IntPtr AvSetMmThreadCharacteristicsA(string TaskName, int& TaskIndex)
  
  [<DllImport("avrt.dll")>]
  extern int AvSetMmThreadPriority(IntPtr AvrtHandle, int AvrtPriority)
  
  [<DllImport("winmm.dll", EntryPoint="timeBeginPeriod")>]
  extern int timeBeginPeriod(uint uPeriod)

    let [<EntryPoint; STAThread>] main _ =
        let mutable taskIndex = 0
        let handle = AvSetMmThreadCharacteristicsA("Games", &taskIndex)
        let setPriorityResult = AvSetMmThreadPriority(handle, 2)
```

Another thing I've tried is using [timeBeginPeriod](https://learn.microsoft.com/en-us/windows/win32/api/timeapi/nf-timeapi-timebeginperiod) to set the timer precision to 1ms, and also using [Sleep](https://learn.microsoft.com/en-us/windows/win32/api/synchapi/nf-synchapi-sleep) from Synchapi.h, in place of all the `System.Threading.Sleep` calls, though that didn't work either. The docs suggest it should, as this `Sleep`, if it isn't the same one that `System.Threading.Sleep` calls under the hood, honors what you set in `timeBeginPeriod`.

One more thing to try, though it could be a bit of an overhaul, is to replace the main loop (and the render loop?) with a timer callback using [CreateTimerQueueTimer](https://learn.microsoft.com/en-us/windows/win32/api/threadpoollegacyapiset/nf-threadpoollegacyapiset-createtimerqueuetimer?redirectedfrom=MSDN).

**Comment by reinux** [comment]
For reference:

[A C# wrapper around timeSetEvent and other MMTimer functions](https://github.com/metaseed/MetaStudio/blob/master/src/Metaseed.Core/Win32/MMTimer.cs)

[An interesting rant about timers and QueryPerformanceCounter from 2007](http://algo2.iti.kit.edu/wassenberg/timing/timing_pitfalls.pdf), which I think is no longer an issue due to [QPC using the High Precision Event Timer device](https://learn.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps) now choosing the best hardware on the fly.

**Comment by bryanedds** [comment]
We've made a couple of changes, specifically not spinning in the render thread. Elmario and other extremely low resource-utilization Nu programs no longer exhibit the forementioned choppiness.

**Comment by bryanedds** [comment]
Haven't seen any sign of this in a long time. Closing.
